## YAML Template.
---
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enable: false
        
sever: 
    port: 48152
    
custom: 
    custom.activeprofileName: production
    
spring:
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:customer
        username: sa
        password: qwerty
        driver-class-name: org.h2.Driver
    h2:
        console:
            enable: true